### ISSUE TITLE
Missing resource name causes plugin to fail

### ISSUE THREAD

**Issue by bwilder** [awslabs/aws-cfn-lint-visual-studio-code#16]
Hi,
While attempting to use cfn-python-lint (`cfn-lint 0.4.1`) with aws-cfn-lint-visual-studio-code (`vscode-cfn-lint 0.2.0`) I found the extension consistently crashing with my sample template:

> Settings have been updated...
> Settings: {"cfnLint":{"path":"/usr/local/bin/cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
> Is CFN: true
> running............. /usr/local/bin/cfn-lint --format,json,--template,/Users/MYUSER/Test/test.yaml
> 2018-07-23 08:23:17,194 - cfnlint - ERROR - Tried to process rules on file /Users/MYUSER/Test/test.yaml but got an error: 'str_node' object has no attribute 'get'
> 
> child process exited with code 1 and signal null
> undefined:1
> 
> SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at ChildProcess.<anonymous> (/Users/MYUSER/.vscode/extensions/kddejong.vscode-cfn-lint-0.2.0/server/out/server.js:150:28)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:194:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

YAML source:
```yaml
---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Test description"
Resources:
  Properties:
    BucketName: "bucket_test"
  Type: "AWS::S3::Bucket"
```

Eventually I realized I didn't have a resource name and resolved the issue, however, it took several application restarts to sort it out. Any chance you could make the extension handle this situation more gracefully?

Final YAML:
```yaml
---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Test description"
Resources:
  TestS3Bucket:
    Properties:
      BucketName: "bucket_test"
    Type: "AWS::S3::Bucket"
```
