### ISSUE TITLE
Having issues with more complex templates (e.g. !Ref, FindInMap, !If )

### ISSUE THREAD

**Issue by mraliagha** [awslabs/aws-cfn-lint-visual-studio-code#46]
I have installed this extension on Visual Studio Code. Although it is installed properly, the plugin does not recognize more advanced templates. Is that correct or I am missing some part of the installation? 

For example, every tag starts with "!" is unknown including the following tags:
!Ref
!FindInMap
!If

**Comment by kddejong** [comment]
@mraliagha when cfn-lint provides errors it will do so by prefixing them with `cfn-lint`.  Can you provide the full error so I can validate its cfn-lint thats causing it.  Usually we see this issue when people are using the generic yaml plugin is as well as it doesn't know about the CloudFormation tags.  One thing you could do is configure that plugin to know what the CloudFormation Tags are.  In settings just do this.

```
"yaml.customTags": [
        "!And",
        "!If",
        "!Not",
        "!Equals",
        "!Or",
        "!FindInMap",
        "!Base64",
        "!Cidr",
        "!Ref",
        "!Sub",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!Select",
        "!Split",
        "!Join"
    ],
```

**Comment by waynerobinson** [comment]
I've also just installed the package and seem to have similar issues.

A more complete example, which is providing a `bad indentation of mapping entry` error on the closing square-bracket after the `AvailabilityZone: !Select [0, !GetAZs ""]`.

This template deploys fine and I can't see why there would be an error.

```yaml
Resources:
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet (AZ1)
```

My `settings.json`:

```json
    // Custom tags for the parser to use
    "yaml.customTags": [
        "!And",
        "!If",
        "!Not",
        "!Equals",
        "!Or",
        "!FindInMap",
        "!Base64",
        "!Cidr",
        "!Ref",
        "!Sub",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!Select",
        "!Split",
        "!Join"
    ],
    
    // Enable/disable default YAML formatter (requires restart)
    "yaml.format.enable": true,

    "cfnLint.path": "/usr/local/bin/cfn-lint"
```

The version of `cfn-lint` is `0.18.1`.

When I run it against the YAML file directly it doens't raise these errors.
